name: Build

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
            node-version: 18.x

      - name: Install packages
        run: npm ci

      - name: Install build
        run: npm run build