name: Main pipeline for Capstone

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
        config-path:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
            node-version: 18.x
  
      - name: Install packages
        run: npm ci

      - name: Install build
        run: npm run build

      - name: Unit testing
        run: npm test

  deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    needs: [build]
