name: Main pipeline for Capstone

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
        config-path:
          required: true
          type: string

jobs:
  testing:
    uses: ./.github/workflows/testing.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    needs: [testing]

  deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    needs: [build]
