name: Testing

on: [workflow_call]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2
    
        - name: Use Node 18
          uses: actions/setup-node@v3
          with:
              node-version: 18.x

        - name: Unit testing
          run: npm test